blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/maziggy/bambuddy-wiki
    about: Check the documentation for guides and troubleshooting
  - name: Community Forum
    url: https://forum.bambuddy.cool
    about: Ask questions and share ideas with the community
