import json

actions: dict[str, dict[str, list[str]]] = {}

# load from backend/app/data/hms_actions.json
with open("backend/app/data/hms_actions.json") as f:
    actions = json.load(f)


class HMSAction:
    RESUME_PRINTING = "RESUME_PRINTING"
    RESUME_PRINTING_DEFECTS = "RESUME_PRINTING_DEFECTS"
    RESUME_PRINTING_PROBELM_SOLVED = "RESUME_PRINTING_PROBELM_SOLVED"
    STOP_PRINTING = "STOP_PRINTING"
    CHECK_ASSISTANT = "CHECK_ASSISTANT"
    FILAMENT_EXTRUDED = "FILAMENT_EXTRUDED"
    RETRY_FILAMENT_EXTRUDED = "RETRY_FILAMENT_EXTRUDED"
    CONTINUE = "CONTINUE"
    LOAD_VIRTUAL_TRAY = "LOAD_VIRTUAL_TRAY"
    OK_BUTTON = "OK_BUTTON"
    FILAMENT_LOAD_RESUME = "FILAMENT_LOAD_RESUME"
    JUMP_TO_LIVEVIEW = "JUMP_TO_LIVEVIEW"
    NO_REMINDER_NEXT_TIME = "NO_REMINDER_NEXT_TIME"
    REFRESH_NOZZLE = "REFRESH_NOZZLE"
    IGNORE_NO_REMINDER_NEXT_TIME = "IGNORE_NO_REMINDER_NEXT_TIME"
    IGNORE_RESUME = "IGNORE_RESUME"
    PROBLEM_SOLVED_RESUME = "PROBLEM_SOLVED_RESUME"
    TURN_OFF_FIRE_ALARM = "TURN_OFF_FIRE_ALARM"
    RETRY_PROBLEM_SOLVED = "RETRY_PROBLEM_SOLVED"
    STOP_DRYING = "STOP_DRYING"
    CANCLE = "CANCLE"  # Note: "CANCLE" is intentionally misspelled in the BambuStudio source code
    REMOVE_CLOSE_BTN = "REMOVE_CLOSE_BTN"
    PROCEED = "PROCEED"
    OK_JUMP_RACK = "OK_JUMP_RACK"
    ABORT = "ABORT"
    DISABLE_PURIFICATION = "DISABLE_PURIFICATION"
    DONT_REMIND_NEXT_TIME = "DONT_REMIND_NEXT_TIME"
    DBL_CHECK_CANCEL = "DBL_CHECK_CANCEL"
    DBL_CHECK_DONE = "DBL_CHECK_DONE"
    DBL_CHECK_RETRY = "DBL_CHECK_RETRY"
    DBL_CHECK_RESUME = "DBL_CHECK_RESUME"
    DBL_CHECK_OK = "DBL_CHECK_OK"


HMS_ID_TO_ACTION_NAME_MAP: dict[int, str] = {
    2: HMSAction.RESUME_PRINTING,
    3: HMSAction.RESUME_PRINTING_DEFECTS,
    4: HMSAction.RESUME_PRINTING_PROBELM_SOLVED,
    5: HMSAction.STOP_PRINTING,
    6: HMSAction.CHECK_ASSISTANT,
    7: HMSAction.FILAMENT_EXTRUDED,
    8: HMSAction.RETRY_FILAMENT_EXTRUDED,
    9: HMSAction.CONTINUE,
    10: HMSAction.LOAD_VIRTUAL_TRAY,
    11: HMSAction.OK_BUTTON,
    12: HMSAction.FILAMENT_LOAD_RESUME,
    13: HMSAction.JUMP_TO_LIVEVIEW,
    23: HMSAction.NO_REMINDER_NEXT_TIME,
    24: HMSAction.REFRESH_NOZZLE,
    25: HMSAction.IGNORE_NO_REMINDER_NEXT_TIME,
    27: HMSAction.IGNORE_RESUME,
    28: HMSAction.PROBLEM_SOLVED_RESUME,
    29: HMSAction.TURN_OFF_FIRE_ALARM,
    34: HMSAction.RETRY_PROBLEM_SOLVED,
    35: HMSAction.STOP_DRYING,
    37: HMSAction.CANCLE,  # Note: "CANCLE" is misspelled in the BambuStudio source code
    39: HMSAction.REMOVE_CLOSE_BTN,
    41: HMSAction.PROCEED,
    49: HMSAction.OK_JUMP_RACK,
    51: HMSAction.ABORT,
    54: HMSAction.DISABLE_PURIFICATION,
    57: HMSAction.DONT_REMIND_NEXT_TIME,
    10000: HMSAction.DBL_CHECK_CANCEL,
    10001: HMSAction.DBL_CHECK_DONE,
    10002: HMSAction.DBL_CHECK_RETRY,
    10003: HMSAction.DBL_CHECK_RESUME,
    10004: HMSAction.DBL_CHECK_OK,
}

REVERSED_HMS_ACTION_NAME_TO_ID_MAP: dict[str, int] = {v: k for k, v in HMS_ID_TO_ACTION_NAME_MAP.items()}


def get_action_name_from_id(action_id: int) -> str:
    return HMS_ID_TO_ACTION_NAME_MAP.get(action_id, f"UNKNOWN_ACTION_{action_id}")


def get_actions_for_error_code(device: str, error_code: str) -> list[str]:
    return actions.get(device, {}).get(error_code, [])
