"""Default spool and color catalog entries."""

# (name, weight_in_grams)
DEFAULT_SPOOL_CATALOG: list[tuple[str, int]] = [
    ("3D FilaPrint - Cardboard", 210),
    ("3D FilaPrint - Plastic", 238),
    ("3D Fuel - Plastic", 264),
    ("3D Power - Plastic", 220),
    ("3D Solutech - Plastic", 173),
    ("3DE - Cardboard", 136),
    ("3DE - Plastic", 181),
    ("3DHOJOR - Cardboard", 157),
    ("3DJake - Cardboard", 209),
    ("3DJake - Plastic", 232),
    ("3DJake 250g - Plastic", 91),
    ("3DJake ecoPLA - Plastic", 210),
    ("3DXTech - Plastic", 258),
    ("Acccreate - Plastic", 161),
    ("Amazon Basics - Plastic", 234),
    ("Amolen - Plastic", 150),
    ("AMZ3D - Plastic", 233),
    ("Anycubic - Cardboard", 125),
    ("Anycubic - Plastic", 127),
    ("Atomic Filament - Plastic", 272),
    ("Aurapol - Plastic", 220),
    ("Azure Film - Plastic", 163),
    ("Bambu Lab - Plastic High Temp", 216),
    ("Bambu Lab - Plastic Low Temp", 250),
    ("Bambu Lab - Plastic White", 253),
    ("BQ - Plastic", 218),
    ("Colorfabb - Plastic", 236),
    ("Colorfabb 750g - Cardboard", 152),
    ("Colorfabb 750g - Plastic", 254),
    ("Comgrow - Cardboard", 166),
    ("Creality - Cardboard", 180),
    ("Creality - Plastic", 135),
    ("Das Filament - Plastic", 211),
    ("Devil Design - Plastic", 256),
    ("Duramic 3D - Cardboard", 136),
    ("Elegoo - Cardboard", 153),
    ("Elegoo - Plastic", 111),
    ("Eryone - Cardboard", 156),
    ("Eryone - Plastic", 187),
    ("eSUN - Cardboard", 147),
    ("eSUN - Plastic", 240),
    ("eSUN 2.5kg - Plastic", 634),
    ("Extrudr - Plastic", 244),
    ("Fiberlogy - Plastic", 260),
    ("Filament PM - Plastic", 224),
    ("Fillamentum - Plastic", 230),
    ("Flashforge - Plastic", 167),
    ("FormFutura - Cardboard", 155),
    ("FormFutura 750g - Plastic", 212),
    ("Geeetech - Plastic", 178),
    ("Gembird - Cardboard", 143),
    ("Hatchbox - Plastic", 225),
    ("Inland - Cardboard", 142),
    ("Inland - Plastic", 210),
    ("Jayo - Cardboard", 120),
    ("Jayo - Plastic", 126),
    ("Jayo 250g - Plastic", 58),
    ("Kingroon - Cardboard", 155),
    ("Kingroon - Plastic", 156),
    ("KVP - Plastic", 263),
    ("Matter Hackers - Plastic", 215),
    ("MG Chemicals - Cardboard", 150),
    ("MG Chemicals - Plastic", 239),
    ("Mika3D - Plastic", 175),
    ("MonoPrice - Plastic", 221),
    ("Overture - Cardboard", 150),
    ("Overture - Plastic", 237),
    ("PolyMaker - Cardboard", 137),
    ("PolyMaker - Plastic", 220),
    ("PolyMaker 3kg - Cardboard", 418),
    ("PolyTerra PLA - Cardboard", 147),
    ("PrimaSelect - Plastic", 222),
    ("ProtoPasta - Cardboard", 80),
    ("Prusament - Plastic", 201),
    ("Prusament - Plastic w/ Cardboard Core", 196),
    ("Rosa3D - Plastic", 245),
    ("Sakata3D - Plastic", 205),
    ("Snapmaker - Cardboard", 148),
    ("Sovol - Cardboard", 145),
    ("Spectrum - Cardboard", 180),
    ("Spectrum - Plastic", 257),
    ("Sunlu - Plastic", 117),
    ("Sunlu - Plastic V2", 165),
    ("Sunlu - Plastic V3", 179),
    ("Sunlu 250g - Plastic", 55),
    ("UltiMaker - Plastic", 235),
    ("Voolt3D - Plastic", 190),
    ("Voxelab - Plastic", 171),
    ("Wanhao - Plastic", 267),
    ("Ziro - Plastic", 166),
    ("ZYLtech - Plastic", 179),
]

# (manufacturer, color_name, hex_color, material)
DEFAULT_COLOR_CATALOG: list[tuple[str, str, str, str]] = [
    # Bambu Lab PLA Basic
    ("Bambu Lab", "Jade White", "#FFFFFF", "PLA Basic"),
    ("Bambu Lab", "Black", "#000000", "PLA Basic"),
    ("Bambu Lab", "Silver", "#A6A9AA", "PLA Basic"),
    ("Bambu Lab", "Light Gray", "#C0C0C0", "PLA Basic"),
    ("Bambu Lab", "Gray", "#8E9089", "PLA Basic"),
    ("Bambu Lab", "Dark Gray", "#616364", "PLA Basic"),
    ("Bambu Lab", "Red", "#C12E1F", "PLA Basic"),
    ("Bambu Lab", "Magenta", "#EC008C", "PLA Basic"),
    ("Bambu Lab", "Hot Pink", "#FF69B4", "PLA Basic"),
    ("Bambu Lab", "Pink", "#F55A74", "PLA Basic"),
    ("Bambu Lab", "Beige", "#F7E6DE", "PLA Basic"),
    ("Bambu Lab", "Yellow", "#FFFF00", "PLA Basic"),
    ("Bambu Lab", "Sunflower Yellow", "#FEC600", "PLA Basic"),
    ("Bambu Lab", "Gold", "#E4BD68", "PLA Basic"),
    ("Bambu Lab", "Orange", "#FF8C00", "PLA Basic"),
    ("Bambu Lab", "Pumpkin Orange", "#FF9016", "PLA Basic"),
    ("Bambu Lab", "Bright Green", "#66FF00", "PLA Basic"),
    ("Bambu Lab", "Bambu Green", "#00AE42", "PLA Basic"),
    ("Bambu Lab", "Mistletoe Green", "#3F8E43", "PLA Basic"),
    ("Bambu Lab", "Turquoise", "#00B1B7", "PLA Basic"),
    ("Bambu Lab", "Cyan", "#0086D6", "PLA Basic"),
    ("Bambu Lab", "Blue", "#0A2989", "PLA Basic"),
    ("Bambu Lab", "Blue Grey", "#647988", "PLA Basic"),
    ("Bambu Lab", "Cobalt Blue", "#0047AB", "PLA Basic"),
    ("Bambu Lab", "Purple", "#5E43B7", "PLA Basic"),
    ("Bambu Lab", "Indigo Purple", "#482960", "PLA Basic"),
    ("Bambu Lab", "Brown", "#9D432C", "PLA Basic"),
    ("Bambu Lab", "Cocoa Brown", "#5C4033", "PLA Basic"),
    ("Bambu Lab", "Bronze", "#847D48", "PLA Basic"),
    # Bambu Lab PLA Matte
    ("Bambu Lab", "Ivory White", "#EBEBE3", "PLA Matte"),
    ("Bambu Lab", "Bone White", "#F5F5DC", "PLA Matte"),
    ("Bambu Lab", "Lemon Yellow", "#FFF44F", "PLA Matte"),
    ("Bambu Lab", "Mandarin Orange", "#FF7518", "PLA Matte"),
    ("Bambu Lab", "Scarlet Red", "#FF2400", "PLA Matte"),
    ("Bambu Lab", "Lilac Purple", "#C8A2C8", "PLA Matte"),
    ("Bambu Lab", "Grape Purple", "#6F2DA8", "PLA Matte"),
    ("Bambu Lab", "Grass Green", "#6BB173", "PLA Matte"),
    ("Bambu Lab", "Dark Green", "#656A4D", "PLA Matte"),
    ("Bambu Lab", "Sakura Pink", "#EAB8CA", "PLA Matte"),
    ("Bambu Lab", "Charcoal", "#36454F", "PLA Matte"),
    # Bambu Lab PLA Silk
    ("Bambu Lab", "Blue", "#4F9CCC", "PLA Silk"),
    ("Bambu Lab", "Gold", "#CFB53B", "PLA Silk"),
    ("Bambu Lab", "Silver", "#C0C0C0", "PLA Silk"),
    ("Bambu Lab", "Copper", "#B87333", "PLA Silk"),
    ("Bambu Lab", "Green", "#50C878", "PLA Silk"),
    ("Bambu Lab", "Red", "#DC143C", "PLA Silk"),
    # Bambu Lab PLA Sparkle
    ("Bambu Lab", "Alpine Green Sparkle", "#4F6359", "PLA Sparkle"),
    ("Bambu Lab", "Galaxy Black Sparkle", "#1C1C1C", "PLA Sparkle"),
    ("Bambu Lab", "Space Gray Sparkle", "#4A4A4A", "PLA Sparkle"),
    # Bambu Lab PETG Basic
    ("Bambu Lab", "Black", "#000000", "PETG Basic"),
    ("Bambu Lab", "White", "#FFFFFF", "PETG Basic"),
    ("Bambu Lab", "Gray", "#808080", "PETG Basic"),
    ("Bambu Lab", "Translucent", "#F0F0F0", "PETG Basic"),
    # Bambu Lab PETG-HF
    ("Bambu Lab", "White", "#F0F1F0", "PETG-HF"),
    ("Bambu Lab", "Black", "#000000", "PETG-HF"),
    ("Bambu Lab", "Gray", "#A3A6A6", "PETG-HF"),
    ("Bambu Lab", "Red", "#C33F45", "PETG-HF"),
    ("Bambu Lab", "Orange", "#FF7146", "PETG-HF"),
    ("Bambu Lab", "Blue", "#1E90FF", "PETG-HF"),
    ("Bambu Lab", "Translucent Orange", "#EF8E5B", "PETG-HF"),
    # Bambu Lab ABS
    ("Bambu Lab", "Black", "#000000", "ABS"),
    ("Bambu Lab", "White", "#FFFFFF", "ABS"),
    ("Bambu Lab", "Gray", "#808080", "ABS"),
    ("Bambu Lab", "Red", "#FF0000", "ABS"),
    # Bambu Lab ASA
    ("Bambu Lab", "Black", "#000000", "ASA"),
    ("Bambu Lab", "White", "#FFFFFF", "ASA"),
    ("Bambu Lab", "Gray", "#808080", "ASA"),
    # Bambu Lab TPU
    ("Bambu Lab", "White", "#F0EFE3", "TPU 95A"),
    ("Bambu Lab", "Black", "#000000", "TPU 95A"),
    ("Bambu Lab", "Gray", "#8C9091", "TPU 95A"),
    ("Bambu Lab", "Red", "#FF0000", "TPU 95A"),
    # Bambu Lab PLA-CF / PAHT-CF / PETG-CF
    ("Bambu Lab", "Black", "#1A1A1A", "PLA-CF"),
    ("Bambu Lab", "Black", "#1A1A1A", "PAHT-CF"),
    ("Bambu Lab", "Black", "#1A1A1A", "PETG-CF"),
    # Bambu Lab Support Materials
    ("Bambu Lab", "Natural", "#F5F5DC", "PLA Support"),
    ("Bambu Lab", "Natural", "#F5F5DC", "PVA Support"),
    # Polymaker PolyTerra PLA
    ("Polymaker", "Cotton White", "#F5F5F5", "PolyTerra PLA"),
    ("Polymaker", "Charcoal Black", "#2B2B2B", "PolyTerra PLA"),
    ("Polymaker", "Marble White", "#E8E8E8", "PolyTerra PLA"),
    ("Polymaker", "Fossil Grey", "#6B6B6B", "PolyTerra PLA"),
    ("Polymaker", "Shadow Black", "#1A1A1A", "PolyTerra PLA"),
    ("Polymaker", "Army Red", "#8B0000", "PolyTerra PLA"),
    ("Polymaker", "Lava Red", "#CF1020", "PolyTerra PLA"),
    ("Polymaker", "Sakura Pink", "#FFB7C5", "PolyTerra PLA"),
    ("Polymaker", "Rose", "#FF007F", "PolyTerra PLA"),
    ("Polymaker", "Peach", "#FFCBA4", "PolyTerra PLA"),
    ("Polymaker", "Banana", "#FFE135", "PolyTerra PLA"),
    ("Polymaker", "Savannah Yellow", "#F4C430", "PolyTerra PLA"),
    ("Polymaker", "Sunrise Orange", "#FF6600", "PolyTerra PLA"),
    ("Polymaker", "Muted Green", "#4F7942", "PolyTerra PLA"),
    ("Polymaker", "Forest Green", "#228B22", "PolyTerra PLA"),
    ("Polymaker", "Mint", "#98FF98", "PolyTerra PLA"),
    ("Polymaker", "Lavender Purple", "#B57EDC", "PolyTerra PLA"),
    ("Polymaker", "Sapphire Blue", "#0F52BA", "PolyTerra PLA"),
    ("Polymaker", "Ice", "#D6ECEF", "PolyTerra PLA"),
    # Prusament PLA
    ("Prusament", "Jet Black", "#1A1A1A", "PLA"),
    ("Prusament", "Galaxy Black", "#1F1F1F", "PLA"),
    ("Prusament", "Pristine White", "#FFFFFF", "PLA"),
    ("Prusament", "Gentleman's Grey", "#5A5A5A", "PLA"),
    ("Prusament", "Lipstick Red", "#C21E1E", "PLA"),
    ("Prusament", "Orange", "#FF6600", "PLA"),
    ("Prusament", "Pineapple Yellow", "#FFD700", "PLA"),
    ("Prusament", "Jungle Green", "#29AB87", "PLA"),
    ("Prusament", "Azure Blue", "#007FFF", "PLA"),
    ("Prusament", "Royal Blue", "#4169E1", "PLA"),
    ("Prusament", "Mystic Purple", "#7B68EE", "PLA"),
    # eSUN PLA+
    ("eSUN", "White", "#FFFFFF", "PLA+"),
    ("eSUN", "Black", "#000000", "PLA+"),
    ("eSUN", "Grey", "#808080", "PLA+"),
    ("eSUN", "Red", "#FF0000", "PLA+"),
    ("eSUN", "Blue", "#0000FF", "PLA+"),
    ("eSUN", "Green", "#00FF00", "PLA+"),
    ("eSUN", "Yellow", "#FFFF00", "PLA+"),
    ("eSUN", "Orange", "#FFA500", "PLA+"),
    ("eSUN", "Purple", "#800080", "PLA+"),
    ("eSUN", "Pink", "#FFC0CB", "PLA+"),
    # Hatchbox PLA
    ("Hatchbox", "White", "#FFFFFF", "PLA"),
    ("Hatchbox", "Black", "#000000", "PLA"),
    ("Hatchbox", "Gray", "#808080", "PLA"),
    ("Hatchbox", "Red", "#FF0000", "PLA"),
    ("Hatchbox", "Blue", "#0000FF", "PLA"),
    ("Hatchbox", "Green", "#00FF00", "PLA"),
    ("Hatchbox", "Yellow", "#FFFF00", "PLA"),
    ("Hatchbox", "Orange", "#FFA500", "PLA"),
    ("Hatchbox", "Purple", "#800080", "PLA"),
    ("Hatchbox", "Pink", "#FFC0CB", "PLA"),
    ("Hatchbox", "True Blue", "#0073CF", "PLA"),
    ("Hatchbox", "True Green", "#008000", "PLA"),
]
